version: '3.8'

services:
  app:
    build: .
    ports:
      - 3000:8080
  db:
    image: postgres:latest
    ports:
      - 2345:5432
    environment:
      POSTGRES_DB: 'myDB'
      POSTGRES_USER: 'myUser'
      POSTGRES_PASSWORD: 'abc123'
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
